version: "3.3"

services:
    ansible-control:
        build:
            context: ./
            dockerfile: DockerfileControl       
        networks:
            simple-docker-centos-ansible-vpc:
                ipv4_address: 10.0.5.2        
    ansible-managed:        
        build:
            context: ./
            dockerfile: DockerfileManaged
        networks:
            simple-docker-centos-ansible-vpc:
                ipv4_address: 10.0.5.3
        ports:
            - "22"

networks:
    simple-docker-centos-ansible-vpc:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.5.0/24